version: "3.9"

services:
  proxy:
    image: my-proxy:latest
    deploy:
      mode: replicated
      replicas: 2
    ports:
      - "80:80"
    networks:
      - app-network
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf

  user-auth:
    image: mi_app/user-auth:latest
    networks:
      - app-network

  bus-reservation:
    image: mi_app/bus-reservation:latest
    networks:
      - app-network

  payment-gateway:
    image: mi_app/payment-gateway:latest
    networks:
      - app-network

  route-scheduler:
    image: mi_app/route-scheduler:latest
    networks:
      - app-network

networks:
  app-network:
    driver: overlay

configs:
  nginx_config:
    file: ./proxy/nginx.conf
