---
- name: Configuración Común para Nodos Docker
  hosts: all
  become: yes
  vars:
    repo_url: https://github.com/Revengers777/bus-app.git
    repo_dest: /vagrant/bus-app
    app_build_dir: "{{ repo_dest }}/bus-ticket-app/"
    docker_images:
      - revengers0/my-proxy:latest
      - revengers0/user-auth:latest
      - revengers0/bus-reservation:latest
      - revengers0/payment-gateway:latest
      - revengers0/route-scheduler:latest
    swarm_advertise_addr: "192.168.33.10"

  tasks:
    - name: Actualizar caché de apt
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Instalar paquetes prerequisito (incluyendo git)
      ansible.builtin.apt:
        name: ['curl', 'ca-certificates', 'gnupg', 'lsb-release', 'git']
        state: present

    - name: Clonar el repositorio bus-app
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        clone: yes
        update: yes

    - name: Instalar Docker Compose
      ansible.builtin.shell:
        cmd: |
          sudo mkdir -p /usr/local/lib/docker/cli-plugins
          sudo curl -SL https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-linux-x86_64 -o /usr/local/lib/docker/cli-plugins/docker-compose
          sudo chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
          sudo ln -s /usr/local/lib/docker/cli-plugins/docker-compose /usr/bin/docker-compose
        creates: /usr/bin/docker-compose
      register: docker_compose_installed
      changed_when: docker_compose_installed.stdout != ''
      failed_when: docker_compose_installed.rc != 0
      become: yes
      become_user: root

    - name: Descargar imágenes de Docker desde Docker Hub
      docker_image:
        name: "{{ item }}"
        source: pull
      with_items: "{{ docker_images }}"

    - name: Añadir usuario vagrant al grupo docker
      ansible.builtin.user:
        name: vagrant
        groups: docker
        append: yes
      notify:
        - Reiniciar Servicio Docker  # Notifica al handler para reiniciar el servicio Docker si es necesario

  handlers:
    - name: Reiniciar Servicio Docker
      ansible.builtin.systemd:
        name: docker
        state: restarted
        enabled: yes


