---
- name: Configuración Específica del Nodo Manager (Principal)
  hosts: principal
  become: yes
  vars:
    swarm_join_file: /vagrant/unir_swarm.txt  # Ruta del archivo de unión
    repo_dest: /vagrant/bus-app
    app_build_dir: "{{ repo_dest }}/bus-ticket-app/"
  tasks:
    - name: Construir imágenes de la aplicación con docker compose
      ansible.builtin.command:
        cmd: docker compose build
        chdir: "{{ app_build_dir }}"
      environment:
        COMPOSE_PROJECT_NAME: busapp
      register: compose_build_result
      changed_when: "'Successfully built' in compose_build_result.stdout"

    - name: Inicializar Docker Swarm en el nodo principal (manager)
      ansible.builtin.shell:
        cmd: "docker swarm init --advertise-addr {{ ansible_default_ipv4.address }}"
      register: swarm_init_result
      failed_when: "'This node is already a manager' not in swarm_init_result.stdout"
      changed_when: "'Swarm initialized' in swarm_init_result.stdout"

    - name: Obtener el token de unión del nodo principal para los nodos worker
      ansible.builtin.shell:
        cmd: "docker swarm join-token worker -q"
      register: swarm_join_token
      changed_when: false

    - name: Crear archivo de unión para los nodos worker
      ansible.builtin.copy:
        content: "docker swarm join --token {{ swarm_join_token.stdout }} {{ ansible_default_ipv4.address }}:2377"
        dest: "{{ swarm_join_file }}"
      when: swarm_init_result.changed

- name: Configuración Específica del Nodo Worker
  hosts: all
  become: yes
  vars:
    swarm_join_file: /vagrant/unir_swarm.txt
    repo_dest: /vagrant/bus-app
    app_build_dir: "{{ repo_dest }}/bus-ticket-app/"
  tasks:
    - name: Construir imágenes de la aplicación con docker compose
      ansible.builtin.command:
        cmd: docker compose build
        chdir: "{{ app_build_dir }}"
      environment:
        COMPOSE_PROJECT_NAME: busapp
      register: compose_build_result
      changed_when: "'Successfully built' in compose_build_result.stdout"

    - name: Esperar a que el archivo del comando de unión sea creado por el manager
      ansible.builtin.wait_for:
        path: "{{ swarm_join_file }}"
        state: present
        timeout: 300  # Aumentamos el tiempo de espera a 5 minutos

    - name: Leer el comando de unión desde el archivo
      ansible.builtin.command:
        cmd: "cat {{ swarm_join_file }}"
      register: join_cmd_output
      changed_when: false

    - name: Unirse al Docker Swarm
      ansible.builtin.command:
        cmd: "{{ join_cmd_output.stdout | trim }}"
      register: swarm_join_result
      failed_when: "'Error response from daemon' in swarm_join_result.stderr and 'This node is already part of a swarm' not in swarm_join_result.stderr"
      changed_when: "'This node joined a swarm as a worker' in swarm_join_result.stdout"
