---
# Primero, ejecuta las tareas comunes de configuración (instalar Docker)
- name: Importar playbook común
  ansible.builtin.import_playbook: playbook_common.yml

# Luego, ejecuta las tareas específicas del manager
- name: Configuración Específica del Nodo Manager
  hosts: all
  become: yes
  vars:
    swarm_init_file: /vagrant/swarm_init.txt
    repo_dest: /vagrant/bus-app
    app_build_dir: "{{ repo_dest }}/bus-ticket-app/"  # Directorio para build/deploy
    swarm_advertise_addr: "192.168.33.10"  # Dirección para el anuncio de Swarm
  tasks:
    - name: Inicializar el Docker Swarm
      docker_swarm:
        state: present
        advertise_addr: "{{ swarm_advertise_addr }}"
      register: swarm_init_result
      changed_when: "'Swarm initialized' in swarm_init_result.stdout"
      notify:
        - Crear archivo de unión

    - name: Crear un archivo para la unión de los workers
      ansible.builtin.copy:
        content: "{{ swarm_init_result.stdout | regex_search('docker swarm join.*', '\\0') }}"
        dest: "{{ swarm_init_file }}"
      when: swarm_init_result.changed

    - name: Construir imágenes de la aplicación con Docker Compose
      ansible.builtin.command:
        cmd: docker compose build
        chdir: "{{ app_build_dir }}"
      environment:
        COMPOSE_PROJECT_NAME: busapp
      register: compose_build_result
      changed_when: "'Successfully built' in compose_build_result.stdout"

    - name: Desplegar el servicio de Docker Swarm usando Docker Compose
      ansible.builtin.command:
        cmd: docker stack deploy -c {{ app_build_dir }}/docker-compose.yml busapp
        chdir: "{{ app_build_dir }}"
      register: deploy_result
      changed_when: "'Creating service' in deploy_result.stdout"

    - name: Verificar la creación del servicio
      debug:
        msg: "El servicio ha sido desplegado correctamente"

  handlers:
    - name: Crear archivo de unión
      ansible.builtin.copy:
        content: "{{ swarm_init_result.stdout | regex_search('docker swarm join.*', '\\0') }}"
        dest: "{{ swarm_init_file }}"

