---
- name: Configuración Específica del Nodo Manager
  hosts: all
  become: yes
  vars:
    swarm_join_file: /vagrant/unir_swarm.txt
    manager_ip: 192.168.33.10
    repo_url: https://github.com/Revengers777/bus-app.git
    repo_dest: /vagrant/bus-app
    app_build_dir: "{{ repo_dest }}/bus-ticket-app/"
  tasks:
    - name: Inicializar Docker Swarm
      ansible.builtin.command:
        cmd: "docker swarm init --advertise-addr {{ manager_ip }}"
      register: swarm_init_result
      failed_when: "'Error response from daemon' in swarm_init_result.stderr and 'This node is already part of a swarm' not in swarm_init_result.stderr"
      changed_when: "'Swarm initialized' in swarm_init_result.stdout"

    - name: Extraer la línea de comando exacta para unirse
      ansible.builtin.shell: "docker swarm join-token worker | tail -2 | head -1"
      register: swarm_join_command
      changed_when: false

    - name: Guardar el comando en un archivo
      ansible.builtin.copy:
        content: "{{ swarm_join_command.stdout }}"
        dest: "{{ swarm_join_file }}"

    - name: Instalar Docker Compose
      ansible.builtin.shell: |
        curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
      args:
        creates: /usr/local/bin/docker-compose

    - name: Verificar la instalación de Docker Compose
      ansible.builtin.command:
        cmd: docker-compose --version
      register: docker_compose_version

    - name: Mostrar versión de Docker Compose
      ansible.builtin.debug:
        msg: "Docker Compose instalado correctamente, versión: {{ docker_compose_version.stdout }}"

    - name: Desplegar la aplicación con Docker Compose
      ansible.builtin.command:
        cmd: docker-compose -f docker-compose.yml up -d
        chdir: "{{ app_build_dir }}"

