- name: Configuración Específica del Nodo Manager
  hosts: all
  become: yes
  vars:
    manager_ip: 192.168.33.10
    repo_url: https://github.com/Revengers777/bus-app.git
    repo_dest: /vagrant/bus-app
    app_build_dir: "{{ repo_dest }}/bus-ticket-app/"
  tasks:
    - name: Inicializar Docker Swarm
      ansible.builtin.command:
        cmd: "docker swarm init --advertise-addr {{ manager_ip }}"
      register: swarm_init_result
      failed_when: "'Error response from daemon' in swarm_init_result.stderr and 'This node is already part of a swarm' not in swarm_init_result.stderr"
      changed_when: "'Swarm initialized' in swarm_init_result.stdout"

    - name: Obtener token de worker
      ansible.builtin.shell:
        cmd: "docker swarm join-token -q worker"
      register: worker_token
      changed_when: false

    - name: Establecer token de swarm como variable
      ansible.builtin.set_fact:
        swarm_worker_token: "{{ worker_token.stdout }}"

    - name: Desplegar la aplicación con Docker Compose
      ansible.builtin.command:
        cmd: docker-compose -f docker-compose.yml up -d
        chdir: "{{ app_build_dir }}"

