---
- name: Configuración común para nodos Docker
  hosts: all
  become: yes
  vars:
    repo_url: https://github.com/Revengers777/bus-app.git
    repo_dest: /vagrant/bus-app
    app_build_dir: "{{ repo_dest }}/bus-ticket-app/"

  tasks:
    - name: Actualizar caché de apt
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Instalar paquetes necesarios
      ansible.builtin.apt:
        name:
          - curl
          - ca-certificates
          - gnupg
          - lsb-release
          - git
        state: present

    - name: Clonar repositorio del proyecto
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        clone: yes
        update: yes

    - name: Instalar Docker Compose
      ansible.builtin.shell:
        cmd: |
          mkdir -p /usr/local/lib/docker/cli-plugins
          curl -SL https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-linux-x86_64 -o /usr/local/lib/docker/cli-plugins/docker-compose
          chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
          ln -s /usr/local/lib/docker/cli-plugins/docker-compose /usr/bin/docker-compose
        creates: /usr/bin/docker-compose

    - name: Verificar instalación de Docker Compose
      command: docker-compose --version
      register: docker_compose_version
      ignore_errors: yes

    - name: Mostrar versión de Docker Compose
      debug:
        msg: "Docker Compose está instalado: {{ docker_compose_version.stdout }}"

    - name: Inicializar Docker Swarm en el nodo principal
      when: inventory_hostname == "principal"
      shell: docker swarm init --advertise-addr 192.168.33.10
      register: swarm_init_output
      ignore_errors: yes

