- name: Configuración Específica del Nodo Worker
  hosts: all
  become: yes
  vars:
    swarm_join_file: /vagrant/unir_swarm.txt  # Ruta del archivo generado por el manager
    repo_dest: /vagrant/bus-app  # Directorio donde se clonará el repositorio
    app_build_dir: "{{ repo_dest }}/bus-ticket-app/"  # Directorio para build y despliegue de la app
  tasks:
    - name: Esperar a que el archivo de unión esté disponible
      ansible.builtin.wait_for:
        path: "{{ swarm_join_file }}"
        state: present
        timeout: 120
    
    - name: Leer el comando de unión desde el archivo
      ansible.builtin.command:
        cmd: "cat {{ swarm_join_file }}"
      register: join_cmd_output
      changed_when: false
    
    - name: Unirse al Docker Swarm
      ansible.builtin.command:
        cmd: "{{ join_cmd_output.stdout | trim }}"
      register: swarm_join_result
      failed_when: "'Error response from daemon' in swarm_join_result.stderr and 'This node is already part of a swarm' not in swarm_join_result.stderr"
      changed_when: "'This node joined a swarm as a worker' in swarm_join_result.stdout"

    - name: Construir imágenes de la aplicación con docker compose
      ansible.builtin.command:
        cmd: docker compose build
        chdir: "{{ app_build_dir }}"
      environment:
        COMPOSE_PROJECT_NAME: busapp
      register: compose_build_result
      changed_when: "'Successfully built' in compose_build_result.stdout"

