---
# playbook_common.yml
- name: Configuración Común para Nodos Docker
  hosts: all
  become: yes # La mayoría de las tareas requieren privilegios de root
  vars:
    repo_url: https://github.com/Revengers777/bus-app.git # Usamos tu repositorio
    repo_dest: /vagrant/bus-app # Destino dentro del invitado (corresponde a ./bus-app en el host)
    app_build_dir: "{{ repo_dest }}/bus-ticket-app/" # Directorio para build/deploy

  tasks:
    - name: Actualizar caché de apt
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600 # Actualizar solo si la caché tiene más de 1 hora

    - name: Instalar paquetes prerrequisito (incluyendo git)
      ansible.builtin.apt:
        name: ['curl', 'ca-certificates', 'gnupg', 'lsb-release', 'git']
        state: present

    - name: Clonar el repositorio bus-app
      ansible.builtin.git:
        repo: "{{ repo_url }}"  # Usamos tu repositorio
        dest: "{{ repo_dest }}"  # La carpeta donde clonaremos el repositorio
        clone: yes
        update: yes

    - name: Instalar Docker Compose
      ansible.builtin.shell:
        cmd: |
          sudo mkdir -p /usr/local/lib/docker/cli-plugins
          sudo curl -SL https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-linux-x86_64 -o /usr/local/lib/docker/cli-plugins/docker-compose
          sudo chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
          sudo ln -s /usr/local/lib/docker/cli-plugins/docker-compose /usr/bin/docker-compose
        creates: /usr/bin/docker-compose
      register: docker_compose_installed
      changed_when: docker_compose_installed.stdout != ''
      failed_when: docker_compose_installed.rc != 0
      become: yes
      become_user: root

    - name: Verificar instalación de Docker Compose
      command: docker-compose --version
      register: docker_compose_version
      ignore_errors: yes  # Esto asegura que no falle la tarea si hay un error o una advertencia.

    - name: Mostrar versión de Docker Compose
      debug:
        msg: "Docker Compose está instalado: {{ docker_compose_version.stdout }}"

